### ISSUE TITLE
Feature 1: User can view the list of Ghibli films

### ISSUE THREAD

**Issue by janiicelee** [janiicelee/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the list of Ghibli movies

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the 'susuwatari' image from the front page, they will get access to the page to view all the ghibli movies

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-03-01 at 11 50 27 AM](https://user-images.githubusercontent.com/57986882/156238464-104c3d06-b3a1-4865-a2bb-bb2a47fba2e2.png)
![Screen Shot 2022-03-01 at 11 50 04 AM](https://user-images.githubusercontent.com/57986882/156238481-9f38e428-a1e7-4d24-8251-5b8b025d2514.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make an entry page for the users to get started with the application
- [x] In the entry page, align the text and image to the center
- [x] Make sure that when the user clicks the center image it goes to the list of Ghibli films.
- [x] Make sure the mobile version has one column for showing the movies
- [x] Make sure the desktop version has two columns for showing the movies
- [x] Make two tabs for the list and for the reviews
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
