### ISSUE TITLE
Feature 5: User can delete their reviews

### ISSUE THREAD

**Issue by janiicelee** [janiicelee/ajax-project#10]
## 💰 Motivation

Users will want to delete their reviews

## 📐 Plan

Create a delete button and a confirmation modal so that they can check and delete their review completely.

## 🖼️ Wireframe
![Screen Shot 2022-03-04 at 5 06 15 PM](https://user-images.githubusercontent.com/57986882/156861087-e916dce5-43fd-4e4a-ba18-6b083f3d08a2.png)
![Screen Shot 2022-03-04 at 4 59 53 PM](https://user-images.githubusercontent.com/57986882/156860762-ba919bac-88bb-4026-b8a7-68127eef9724.png)
![Screen Shot 2022-03-04 at 5 00 06 PM](https://user-images.githubusercontent.com/57986882/156860780-7318a456-8261-449c-b6d8-4a4f4eb7cd64.png)

## ✅ Task List

- [x] Add a click target for deleting a review to the form that only appears when the user is editing
- [x] Show a confirmation modal when the user clicks the delete review click target
- [x] Hide the modal when the user clicks the cancel button
- [x] Remove the review from the data model
- [x] Remove the review from the review's DOM tree from the page
- [x] Show the reviews list when the user clicks the delete button
- [x] Revise any HTML or CSS if needed
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
