### ISSUE TITLE
Feature 2: User can view the details of each Ghibli film

### ISSUE THREAD

**Issue by janiicelee** [janiicelee/ajax-project#3]
## 💰 Motivation

Users will want to see the detail information about each Ghibli movie.

## 📐 Plan

Create a detail info page for each movie, and the user can see it when they click the movie poster.

## 🖼️ Wireframes
![Screen Shot 2022-03-01 at 12 41 17 PM](https://user-images.githubusercontent.com/57986882/156245537-df3c3933-e52d-4706-8751-50ec3ecc8f9d.png)
![Screen Shot 2022-03-01 at 12 41 29 PM](https://user-images.githubusercontent.com/57986882/156245548-7c6e745e-b56c-4eaf-b87e-8c866d459229.png)

## ✅ Task List

- [x] Create a layout for the detail info page in HTML.
- [x] Add a 'Go Back' button, so that user can go back to the list page later.
- [x] Make a DOM Tree for the info page, that includes all the information for the movie.
- [x] Listen for 'click' events on each Ghibli film, when the user clicks the poster it should show the matching detail information.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
