### ISSUE TITLE
Feature 3: User can add a review on each film

### ISSUE THREAD

**Issue by janiicelee** [janiicelee/ajax-project#5]
## 💰 Motivation

Users will want to add a review or right down thoughts about the film that they watched.

## 📐 Plan

Create a review page for each film so that users can add a review on it.

## 🖼️ Wireframes
![Screen Shot 2022-03-02 at 3 29 29 PM](https://user-images.githubusercontent.com/57986882/156467119-905e35c9-f1af-4f85-97fa-d45b2f62e88c.png)
![Screen Shot 2022-03-02 at 3 30 32 PM](https://user-images.githubusercontent.com/57986882/156467213-e3e981a8-2971-46d4-8c79-a7ad79b58e7d.png)
![Screen Shot 2022-03-02 at 3 31 37 PM](https://user-images.githubusercontent.com/57986882/156467313-86ca9dbd-0b97-41e9-a067-e7a9036c3af8.png)

## ✅ Task List

- [x] #6
- [x] Create a layout for the review form (or page).
- [x] Listen for click events on the 'Add Review' button so that when user clicks the button it goes to the review page.
- [x] When user submits the review form, each review will be added to the reviews list.
- [x] User should see all the reviews when they click the reviews tab.
- [x] If there is no reviews, when the user clicks the review tab, it will show a message saying "No Reviews Yet!".
- [x] Add each review an 'id' so that user can edit or delete later.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
