### ISSUE TITLE
Feature 4: User can edit their reviews

### ISSUE THREAD

**Issue by janiicelee** [janiicelee/ajax-project#8]
## 💰 Motivation

Users will want to edit their review or add additional thoughts to the movie that they saw.

## 📐 Plan

Create an edit button so that users can go back to the review page and edit their review.

## 🖼️ Wireframes
![Screen Shot 2022-03-04 at 10 50 48 AM](https://user-images.githubusercontent.com/57986882/156824083-0f80f1c9-4a68-4b0d-a1e4-dd5f8a218a8d.png)
![Screen Shot 2022-03-04 at 10 51 30 AM](https://user-images.githubusercontent.com/57986882/156824149-1fcae088-cd31-47b2-a0cb-9a1cc38c9f37.png)

## ✅ Task List

- [x] Add an 'Edit' button in the DOM so that is can be placed below each review that was made
- [x] Make event delegation in the reviews list so that user can click the edit button
- [x] Modify the 'saveReview' function so that it saves the review after it was edited
- [x] Make sure the review is updated after editing
- [x] Revise any HTML or CSS if needed
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
